Draft: Apollo Studio
gooditcollective/base-api pull request #4
Opened 2021-08-31 14:34 UTC by mxseev

## Описание изменений

-

2021-08-31 20:18 UTC, mxseev commented
1. ~Для работы нужно оплатить Apollo Studio, schema scheck платный~, пока включил триал
2. Два новых action (`schema-publish` и `schema-check`) можно было бы запилить в виде обычных npm команд (`schema-publish` при релизе, `schema-check` в тестах), но зачем нам тогда вообще Github Actions? (я, на самом деле, сам до сих пор не понимаю зачем они нам нужны, мы уже и так запускаем тесты при пуше, зачем Github их ещё раз запускает?)
3. Доки и изменения тестов портирую в base (там они тоже нужны) после мержа этого PR.

2021-09-01 00:04 UTC, neoromantic commented
Команды нужны для порядка. Не важно запускаешь ли ты их в actions, или где, все стандартные операции надо складывать в команды. 

А actions нужны потому что код может пушить не только разработчик с локальной машины, но и например напрямую в гитхаб. 

Гитхаб тесты нужны ещё и потому что там условно стандартное окружение, а у разработчиков у всех разное - у кого винда, у кого мак, разные ноды. В общем правильнее наоборот смотреть - в гитхабе это как бы норма, а локально - это оптимизация лично для тебя, чтобы ты раньше узнавал о проблемах, чем тебе гитхаб сообщит. 

Сергей. 

> 31 авг. 2021 г., в 23:18, Max Eliseev ***@***.***> написал(а):
> 
> ﻿
> Для работы нужно оплатить Apollo Studio, schema scheck платный, пока включил триал
> Два новых action (schema-publish и schema-check) можно было бы запилить в виде обычных npm команд (schema-publish при релизе, schema-check в тестах), но зачем нам тогда вообще Github Actions? (я, на самом деле, сам до сих пор не понимаю зачем они нам нужны, мы уже и так запускаем тесты при пуше, зачем Github их ещё раз запускает?)
> Доки и изменения тестов портирую в base (там они тоже нужны) после мержа этого PR.
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-09-01 13:26 UTC, neoromantic requested changes

2021-09-01 13:26 UTC, neoromantic commented on .github/workflows/test-report.yml
> -  push:
Пуш нужен чтобы запускать тесты при новых пушах в тот же PR. Так вроде получается что если ты создашь PR то только при его появлении тест будет запускаться, не так ли? Если так - это не подходит

2021-09-01 13:26 UTC, neoromantic commented on .github/workflows/schema-check.yml
> +    branches: [main]
Не стоит ли чек схемы запускать в ветках? Это же как раз чтобы видеть на что может повлиять изменение схемы.

2021-09-01 13:26 UTC, neoromantic commented on api/index.ts
> +  if (request.method === "OPTIONS") {
А это зачем?

2021-09-01 13:26 UTC, neoromantic commented on docs/development.md
> +Для полноценной интеграции с Apollo Studio также необходимо проставить ещё пару переменных только в Vercel (только в Production сборках):
Не хватает упоминания зачем нужна Студия и какие она даст возможности если ее подключить

2021-09-01 13:26 UTC, neoromantic commented on .github/workflows/schema-check.yml
> +  schema-check:
А оно же будет падать если ключ студии не передан? Можно ли сделать graceful degradation?

2021-09-01 13:26 UTC, neoromantic commented on vercel.json
> +      "headers": [
Не лучше ли это указать в хендлере? Ближе к коду и универсальнее в смысле деплоя

2021-09-01 16:07 UTC, neoromantic commented
Еще вопрос: почему мы репортим схему руками через CLI а не автоматически через Schema Reporting (то что они сами рекомендуют)?

2021-09-01 16:09 UTC, neoromantic commented
> Еще вопрос: почему мы репортим схему руками через CLI а не автоматически через Schema Reporting (то что они сами рекомендуют)?

Если будем делать автоматический репортинг - не забыть поправить задержку: https://www.apollographql.com/docs/apollo-server/api/plugin/schema-reporting/

2021-09-02 01:42 UTC, mxseev commented on .github/workflows/test-report.yml
> -  push:
Нет, они оба запускаются при каждом (не только при первом) пуше в PR

2021-09-02 01:59 UTC, mxseev commented on vercel.json
> +      "headers": [
Странно, сначала указал в хендлере - не работало, вычитал где-то нужно в `vercel.json` указывать, заработало. Сейчас попробовал вернуть в хендлер и оно продолжило работать. 

Возможно это из-то того `OPTIONS` (без него точно не работает, CORS preflight ругается)

2021-09-02 02:11 UTC, mxseev commented on .github/workflows/schema-check.yml
> +    branches: [main]
Так это и есть, `pull_request: branches: [main]` означает, что запускать во всех **PR, которые будут мержиться в main**, а не то, что Action запускается **только в main**

2021-09-02 02:52 UTC, mxseev commented on docs/development.md
> +Для полноценной интеграции с Apollo Studio также необходимо проставить ещё пару переменных только в Vercel (только в Production сборках):
Добавил

2021-09-03 11:33 UTC, mxseev commented on src/server.ts
> +
Да, единственный способ настроить репорт схемы это писать в env (я ожидал эти настройки в конструкторе `ApolloServerPluginSchemaReporting`, но нет, только через env).

https://www.apollographql.com/docs/apollo-server/api/plugin/schema-reporting/

2021-09-03 11:59 UTC, merged