Aвтоматическая генерация GraphQL документации
gooditcollective/base-api pull request #5
Opened 2021-09-01 11:04 UTC by mxseev

## Описание изменений

Реализована автоматическая генерация GraphQL документации с помощью [SpectaQL](https://github.com/anvilco/spectaql). Она генерируется вместе с остальным проектом (параллельно с TS) и складывается в папку `/public/docs` (добавлен в gitignore).

Правда единственный способ её посмотреть это идти в деплой Vercel в `/docs`. Локально только через `vercel dev` (наш собственный `dev-server.ts` пока умеет только Apollo запускать, не знаю, стоит ли тратить время на его допиливание).

2021-09-01 11:06 UTC, mxseev commented
https://base-api-mxseev.vercel.app/docs например

2021-09-01 13:17 UTC, neoromantic commented on .gitignore
> +/public/docs
А почему бы ее не коммитить то? 

По-моему она должна быть в репе

2021-09-01 13:17 UTC, neoromantic commented on spectaql.yaml
> +  - url: https://base-api-mxseev.vercel.app
Мммм. Это как так? Зачем это указывается и как оно будет работать в разных ветках?

Нельзя ли это передавать через ключ из npm? Можно ли вообще не указывать? В общем как избавиться от зашитого адреса?

2021-09-01 15:47 UTC, neoromantic requested changes
А еще не хватает тут example с полной метадатой. Хочу чтобы было. :)

2021-09-01 17:19 UTC, mxseev commented on spectaql.yaml
> +  - url: https://base-api-mxseev.vercel.app
Да, его можно вообще убрать, так и сделаю

2021-09-01 17:44 UTC, mxseev commented on spectaql.yaml
> +  - url: https://base-api-mxseev.vercel.app
Посмотрел исходники spectaql, yaml конфиг он читает по-тупому (то есть переменные туда не передашь), через аргументы адрес тоже не передать (можно передать `introspection.url`, но это немного другое).

Варианты:
1. Оставить зашитый адрес
2. Поставить туда `localhost` (смысла нет, но он соберется без зашитого адреса)
3. Передавать ему не `.graghql` файл со схемой (как сейчас), а адрес сервера, с которого он будет сам брать схему (этот адрес он в т.ч. будет использовать в доках). Но это будет локальный Apollo, то есть опять localhost. 

Пока выберу 2й вариант, но можно настоять на другом

2021-09-01 17:50 UTC, mxseev commented on .gitignore
> +/public/docs
Да и посмотреть их (доки) можно только в Vercel (или `vercel dev`)

2021-09-02 01:38 UTC, mxseev commented
На комменты ответил, чуть подправил, пример metadata с примерами запилил (правда схему пришлось чуть изменить, чтобы полно пример показать)

2021-09-02 12:54 UTC, neoromantic commented on spectaql.yaml
> +  - url: https://base-api-mxseev.vercel.app
Зашитый адрес — ну, это контрпродуктивно же, документация будет левая?

Локалхост — так и не понял.

А че делать?

2021-09-02 13:08 UTC, neoromantic approved these changes
С учетом моих комментов про servers и налаживание конфига - в остальном всё ок!

2021-09-02 13:08 UTC, neoromantic commented on spectaql.yaml
> +  - url: http://localhost:3000
Думаю что сюда надо добавить прод, как в официальной доке:

```
servers:
  - url: https://example.com/graphql
    description: Production
    production: true
```

2021-09-02 13:08 UTC, neoromantic commented on spectaql.yaml
> +  - url: http://localhost:3000
Это же просто урлы которые будут подставляться в examples. Так что все просто — пропиши здесь прод и всё.

2021-09-02 13:08 UTC, neoromantic commented on spectaql.yaml
>    description: Documentation for basic base-api
Добавь пожалуйста все вменяемые поля из официального примера конфига: https://github.com/anvilco/spectaql/blob/main/config-example.yml

Я имею в виду всякие contact и x-intro-items.

2021-09-03 02:14 UTC, merged