Draft: Мониторинг производительности
gooditcollective/base-api pull request #7
Opened 2021-09-06 15:32 UTC by mxseev

## Описание изменений

- [ ] Перенес мутации (папку с ними) к резолверам (так логичнее)
- [ ] Health запросы (empty, slow, fail)
  - [ ] Тесты для них
- [ ] Завести Яндекс.Танк
- [ ] Привязать его к Github Actions

2021-09-08 20:52 UTC, mxseev commented
Так как Github Actions заблочили тесты, Vercel заблочил я.облако с тестами решено оставить только локальные тесты. Запускаются командой npm командой и документированы

2021-09-14 14:05 UTC, neoromantic requested changes
Я так понимаю, реализован только тест на пустые запросы? 

Можем добавить сюда realistic и slow вместе с параметром ошибки? 

Учитывая что у нас появилась БД — запрашивать реалистик хочется прежде всего.

2021-09-15 08:36 UTC, mxseev commented
> Я так понимаю, реализован только тест на пустые запросы?

Да

> Можем добавить сюда realistic и slow вместе с параметром ошибки?

Не вижу особого смысла в slow (хоть и резолвер для него и [реализован](https://github.com/gooditcollective/base-api/blob/feature/act-578/src/resolvers/health/slow.ts))

> Учитывая что у нас появилась БД — запрашивать реалистик хочется прежде всего.

Да, но она (база) в соседнем PR

2021-09-15 12:59 UTC, mxseev commented
Итак, теперь три k6 теста: empty, realistic и slow. Запускаются последовательно через `npm run k6 --url=...`. realistic пока не очень реальный (без базы)

2021-09-15 13:34 UTC, neoromantic approved these changes

2021-09-15 14:20 UTC, merged